import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Providers} from "../store/provider";
import {LoadingProvider} from "../context/loading-context";
import GlobalPageLoading from "../components/global-loading/global-page-loading";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "博客系统",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <LoadingProvider>
          <GlobalPageLoading/>
          <Providers>
              {children}
          </Providers>
      </LoadingProvider>
      </body>
    </html>
  );
}
