import type { Metadata } from "next";
import "./globals.css";
import {Providers} from "../store/provider";
import {LoadingProvider} from "../context/loading-context";
import GlobalPageLoading from "../components/global-loading/global-page-loading";

export const metadata: Metadata = {
    title: "博客系统",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className="font-sans">
        <Providers>
            <LoadingProvider>
                <GlobalPageLoading/>
                {children}
            </LoadingProvider>
        </Providers>
        </body>
        </html>
    );
}
